Hei filter and manifest list fix
palladiumkenya/openmrs-module-kenyaemrorderentry pull request #226
Opened 2022-07-25 15:41 UTC by PatrickWaweru

Hei filter and manifest list fix

2022-07-25 15:49 UTC, ojwanganto requested changes

2022-07-25 16:06 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                "where o.order_action='NEW' and o.concept_id = 1030 and o.date_stopped is null and o.voided=0 and mo.order_id is null and k.identifier_type=7 and k.identifier is not null ";
Ok

2022-07-25 16:44 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                "where o.order_action='NEW' and o.concept_id = 1030 and o.date_stopped is null and o.voided=0 and mo.order_id is null and k.identifier_type=7 and k.identifier is not null ";
Fixed here: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/226/commits/759f8c6dd1e8369fa6cbabf738013eada1446d78

2022-07-26 17:30 UTC, ojwanganto approved these changes

2022-07-26 17:31 UTC, merged