'Print Manifest' fix
palladiumkenya/openmrs-module-kenyaemrorderentry pull request #247
Opened 2022-11-18 16:59 UTC by PatrickWaweru

1. Enable 'Print Manifest' button only after the full manifest is submitted
2. Print manifest order ordered by date and time sent ascending
3. fix sample type bug - select field should only have valid values 
4. make sure an order can only be added once per manifest using a DB unique index

2022-11-18 20:26 UTC, ojwanganto requested changes

2022-11-18 20:26 UTC, ojwanganto commented on omod/src/main/webapp/pages/orders/manifestOrdersHome.gsp
> +            <% if (manifestOrders.size() > 0 && manifest.status.trim().toLowerCase() == 'submitted') { %>
we can check for non-null on status just so we avoid NPE

2022-11-18 20:26 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabwareSystemWebRequest.java
> +                manifestOrder.setDateSent(new Date());
We can add this to CHAI as well. We need the timestamp

2022-11-18 20:26 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabwareSystemWebRequest.java
> +                manifestOrder.setDateSent(new Date());
We can add this to CHAI as well. We need the timestamp

2022-11-21 05:39 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabwareSystemWebRequest.java
> +                manifestOrder.setDateSent(new Date());
This was already added on the CHAI system

2022-11-21 05:40 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/manifestOrdersHome.gsp
> +            <% if (manifestOrders.size() > 0 && manifest.status.trim().toLowerCase() == 'submitted') { %>
Ok

2022-11-21 06:17 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/manifestOrdersHome.gsp
> +            <% if (manifestOrders.size() > 0 && manifest.status.trim().toLowerCase() == 'submitted') { %>
Fixed here: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/247/commits/d038433c3adc553031ba468181f647aff0b14af7

2022-11-21 06:45 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabwareSystemWebRequest.java
> +                manifestOrder.setDateSent(new Date());
This was already added on the CHAI system

2022-11-22 05:51 UTC, ojwanganto approved these changes

2022-11-22 05:51 UTC, merged