Enhance KenyEMR to have a Lab Order for SARI/ILI Samples
palladiumkenya/openmrs-module-kenyaemrorderentry pull request #257
Opened 2023-03-07 06:29 UTC by gabriel090

![nasai1](https://user-images.githubusercontent.com/8075969/223338770-162f3bfd-505d-4023-a9f4-f7292b93b157.png)
![nasal](https://user-images.githubusercontent.com/8075969/223338782-287adf2d-7e14-4c7e-8a38-f574732b12bd.png)
![nasal2](https://user-images.githubusercontent.com/8075969/223338792-9d3730bd-1602-4b52-bc26-a56598bfad7e.png)

2023-03-07 07:50 UTC, makombe requested changes
@gabriel090  I think also you will need to provide custom answers for for results for `Cerebrospinal fluid Cryptococcus antigen assay` test or else there will be no way the results will be captured or entered. The drop down will be blank.

2023-03-07 07:50 UTC, makombe commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/fragment/controller/patientdashboard/CreateLabsOrdersFragmentController.java
> +
Remove the commented out lines

2023-03-07 07:50 UTC, makombe commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/page/controller/LabOrdersPageController.java
> +                ));
Update the comments, I think the concepts are not viral load or cd4 counts related

2023-03-07 07:52 UTC, gabriel090 commented
Ok

On Tue, Mar 7, 2023, 10:50 AM Makombe Kennedy ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @gabriel090 <https://github.com/gabriel090> I think also you will need to
> provide custom answers for for results for Cerebrospinal fluid
> Cryptococcus antigen assay test or else there will be no way the results
> will be captured or entered. The drop down will be blank.
> ------------------------------
>
> In
> omod/src/main/java/org/openmrs/module/kenyaemrorderentry/fragment/controller/patientdashboard/CreateLabsOrdersFragmentController.java
> <https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257#discussion_r1127471429>
> :
>
> > +                " NASAL SWAB", Arrays.asList(
> +                        concService.getConcept(166556), // hiv viral load
> +                        //   concService.getConcept(1305), // hiv viral load Qualitative
>
> The comments here are misleading, you can remove them
> ------------------------------
>
> In
> omod/src/main/java/org/openmrs/module/kenyaemrorderentry/fragment/controller/patientdashboard/CreateLabsOrdersFragmentController.java
> <https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257#discussion_r1127471848>
> :
>
> > +//                conceptService.getConcept(163363),
> +//                conceptService.getConcept(162614),
> +//                conceptService.getConcept(163364)
> +
>
> Remove the commented out lines
> ------------------------------
>
> In
> omod/src/main/java/org/openmrs/module/kenyaemrorderentry/page/controller/LabOrdersPageController.java
> <https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257#discussion_r1127472382>
> :
>
> > +//                conceptService.getConcept(163363),
> +//                conceptService.getConcept(162614),
> +//                conceptService.getConcept(163364)
> +
>
> same here remove the commented out lines
> ------------------------------
>
> In
> omod/src/main/java/org/openmrs/module/kenyaemrorderentry/page/controller/LabOrdersPageController.java
> <https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257#discussion_r1127473985>
> :
>
> > +                        concService.getConcept(166556), // Flu Antigen Test
> +                        //   concService.getConcept(1305), // hiv viral load Qualitative
> +                        concService.getConcept(165895)// cd4 counts
> +                ));
>
> Update the comments, I think the concepts are not viral load or cd4 counts
> related
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257#pullrequestreview-1327808083>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5TVQKIAITLBEIAJPNWPBLW23SDVANCNFSM6AAAAAAVSBUUYQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257/review/1327808083
> @github.com>
>

2023-03-07 07:55 UTC, gabriel090 commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/fragment/controller/patientdashboard/CreateLabsOrdersFragmentController.java
> +                        //   concService.getConcept(1305), // hiv viral load Qualitative
Done Rectified

2023-03-07 08:01 UTC, gabriel090 commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/fragment/controller/patientdashboard/CreateLabsOrdersFragmentController.java
> +                        //   concService.getConcept(1305), // hiv viral load Qualitative
Waiting for Cosmas to give to rectify this Cerebrospinal fluid Cryptococcus antigen assay

2023-05-31 05:13 UTC, makombe commented
@gabriel090  any updates on this ticket? are you still working on it?

2023-05-31 05:16 UTC, gabriel090 commented
It's still on hold

On Wed, May 31, 2023, 8:13 AM Makombe Kennedy ***@***.***>
wrote:

> @gabriel090 <https://github.com/gabriel090> any updates on this ticket?
> are you still working on it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257#issuecomment-1569509353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5TVQIGVJ4EUID73SXHVXDXI3HQPANCNFSM6AAAAAAVSBUUYQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <palladiumkenya/openmrs-module-kenyaemrorderentry/pull/257/c1569509353@
> github.com>
>

2023-05-31 07:53 UTC, closed without merging