KHP3-5065 - LDL to Zero
palladiumkenya/openmrs-module-kenyaemrorderentry pull request #297
Opened 2024-02-20 05:16 UTC by PatrickWaweru

KHP3-5065 - LDL to Zero

2024-02-20 06:42 UTC, ojwanganto requested changes

2024-02-20 06:42 UTC, ojwanganto commented on api/pom.xml
> -		<version>1.6.2</version>
this should be a snapshot still

2024-02-20 06:42 UTC, ojwanganto commented on api/pom.xml
> +                <includes>
what exactly are the new lines adding?

2024-02-20 06:42 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
I think we can rename this variable appropriately. We'll only have one viral load concept going forward.

2024-02-20 06:42 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
same as above

2024-02-20 06:42 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
same as above. I think just call it viral load

2024-02-20 06:42 UTC, ojwanganto commented on api/src/main/resources/liquibase.xml
> +    <changeSet author="pwaweru" id="kenyaemr_order_entry-sp_vl_LDL_to_Zero-20240215-153630" runOnChange="true">
I don't favor this approach. Wondering if we can resort to using a chore that executes the query. The chore will always just run once after which we can drop it in subsequent releases. Evaluate keenly

2024-02-20 06:42 UTC, ojwanganto commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/fragment/controller/manifest/ManifestFormFragmentController.java
> +    public SimpleObject callLdlToZero() {
You can extract this code into a chore and have it executed once during startup. You can drop the stored procedure once the process is done successfully

2024-02-20 06:42 UTC, ojwanganto commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/page/controller/orders/MaintenancePageController.java
> +public class MaintenancePageController {
We'll not need this.

2024-02-20 06:42 UTC, ojwanganto commented on omod/src/main/webapp/pages/orders/labOrdersCompleteResultManifestHome.gsp
> +            [label: "Maintenance", iconProvider: "kenyaui", icon: "", label: "Maintenance", href: ui.pageLink("kenyaemrorderentry", "orders/maintenance")],
We can clean this

2024-02-20 06:42 UTC, ojwanganto commented on omod/src/main/webapp/pages/orders/labOrdersCompleteWithErrorResultsManifestHome.gsp
> +            [label: "Maintenance", iconProvider: "kenyaui", icon: "", label: "Maintenance", href: ui.pageLink("kenyaemrorderentry", "orders/maintenance")],
...and this

2024-02-20 06:42 UTC, ojwanganto commented on omod/src/main/webapp/pages/orders/maintenance.gsp
> +<%
we'll not need this

2024-02-20 06:42 UTC, ojwanganto commented
Please start handling the changes. I will give you a call for a walkthrough

2024-02-20 09:31 UTC, PatrickWaweru commented on api/pom.xml
> -		<version>1.6.2</version>
Ok. Fixed.

2024-02-20 09:33 UTC, PatrickWaweru commented on api/pom.xml
> +                <includes>
New SQL script as a resource. It should not be filtered as filtering might modify the script.

2024-02-20 09:34 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
I agree. It is work in progress.

2024-02-20 09:34 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
noted

2024-02-20 09:34 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
noted

2024-02-20 09:35 UTC, PatrickWaweru commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/page/controller/orders/MaintenancePageController.java
> +public class MaintenancePageController {
Agreed

2024-02-20 09:36 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/labOrdersCompleteResultManifestHome.gsp
> +            [label: "Maintenance", iconProvider: "kenyaui", icon: "", label: "Maintenance", href: ui.pageLink("kenyaemrorderentry", "orders/maintenance")],
Ok

2024-02-20 09:36 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/maintenance.gsp
> +<%
Agreed

2024-02-20 09:36 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/labOrdersCompleteWithErrorResultsManifestHome.gsp
> +            [label: "Maintenance", iconProvider: "kenyaui", icon: "", label: "Maintenance", href: ui.pageLink("kenyaemrorderentry", "orders/maintenance")],
Ok

2024-02-20 09:37 UTC, PatrickWaweru commented on api/src/main/resources/liquibase.xml
> +    <changeSet author="pwaweru" id="kenyaemr_order_entry-sp_vl_LDL_to_Zero-20240215-153630" runOnChange="true">
Ok

2024-02-20 11:08 UTC, PatrickWaweru commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/fragment/controller/manifest/ManifestFormFragmentController.java
> +    public SimpleObject callLdlToZero() {
Done: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/297/commits/52271d0e14606409ecca71a24c0faa1d2006f5dc

2024-02-20 11:08 UTC, PatrickWaweru commented on omod/src/main/java/org/openmrs/module/kenyaemrorderentry/page/controller/orders/MaintenancePageController.java
> +public class MaintenancePageController {
Done: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/297/commits/52271d0e14606409ecca71a24c0faa1d2006f5dc

2024-02-20 11:09 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/labOrdersCompleteResultManifestHome.gsp
> +            [label: "Maintenance", iconProvider: "kenyaui", icon: "", label: "Maintenance", href: ui.pageLink("kenyaemrorderentry", "orders/maintenance")],
Done: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/297/commits/52271d0e14606409ecca71a24c0faa1d2006f5dc

2024-02-20 11:09 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/labOrdersCompleteWithErrorResultsManifestHome.gsp
> +            [label: "Maintenance", iconProvider: "kenyaui", icon: "", label: "Maintenance", href: ui.pageLink("kenyaemrorderentry", "orders/maintenance")],
Done: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/297/commits/52271d0e14606409ecca71a24c0faa1d2006f5dc

2024-02-20 11:09 UTC, PatrickWaweru commented on omod/src/main/webapp/pages/orders/maintenance.gsp
> +<%
Done: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/297/commits/52271d0e14606409ecca71a24c0faa1d2006f5dc

2024-02-20 12:06 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
Done: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/297/commits/b70e89b9f228cc05cf039ef61f44e240e5bb29b3

2024-02-20 12:06 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrorderentry/labDataExchange/LabOrderDataExchange.java
> +                            conceptToRetain = vlTestConceptQuantitative;
Done: https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry/pull/297/commits/b70e89b9f228cc05cf039ef61f44e240e5bb29b3

2024-02-21 08:26 UTC, ojwanganto commented
Have you tested and confirmed that this works well?

2024-02-22 17:56 UTC, ojwanganto approved these changes

2024-02-22 17:57 UTC, ojwanganto commented
Please test it in a large db and get to know how long it takes

2024-02-22 17:57 UTC, merged